### ISSUE TITLE
3. Allow a different extracted file naming scheme

### ISSUE THREAD

**Issue by gleporeNARA** [tballison/commoncrawl-fetcher-lite#29]
Going to vote for preserving the original file extension for the file naming scheme. When coming up with formats that need signatures created having the original file extension is a good way to do a first pass in splitting the files up into groups of similar files. Otherwise it's just a bunch of numbers and letters.

This is particularly useful when pulling application/octet-stream files.

**Comment by gleporeNARA** [comment]
Thinking about this some more, the rest of the original file name also has value for figuring out the file format. File names like 1-butanol_PROTON-1-1.jdf and Comfortaa-Regular-LGR-Slanted.vf give hints about the contents of the file, and allow us to trace an original file back to a specific website (which we can also do through the index file or the extracted-urls.csv file).

However, appending something to the original file names so as to avoid duplicate file names brings the possibility of running into filesystem limits. Tricky.

**Comment by tballison** [comment]
It is tricky. After dealing with this again and again, I’ve defaulted to
current setup: file hashes as names and a sidecar table with source urls.

Other issue is that if you don’t use hashes as filenames, you’ll wind up w
a bunch of duplicates.

**Comment by gleporeNARA** [comment]
Agreed, I've got some ugly hacks to rename the files based on the values in extracted-urls. I guess that will work.

**Comment by gleporeNARA** [comment]
Yes.
